apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-001
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pv-volume-001"
