apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-externalname
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      environment: testing-externalname
  template:
    metadata:
      labels:
        app: nginx
        environment: testing-externalname
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
